<a href="https://colab.research.google.com/github/suvitha007/project_1-cross-market-analysis/blob/main/myproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CROSS MARKET ANALYSIS

In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.1.4)

In [ ]:
import requests

all_data = []


for page in range(1, 6):

    url =f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page={page}&sparkline=False"

    print(f"Fetching Page {page}...")

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        all_data.extend(data)   # Add page data
    else:
        print("Error:", response.status_code)
        break

print("Total Data Collected:", len(all_data))

Fetching Page 1...
Fetching Page 2...
Fetching Page 3...
Error: 429
Total Data Collected: 500

In [ ]:
len(all_data)

500

In [ ]:
import pandas as pd
df = pd.DataFrame(all_data)
df.to_csv("cryptodata.csv", index=False)

In [ ]:
for i in data:
  print(i)

{'id': 'frax-usd', 'symbol': 'frxusd', 'name': 'Frax USD', 'image': 'https://coin-images.coingecko.com/coins/images/53963/large/frxUSD.png?1737792154', 'current_price': 90.71, 'market_cap': 10262594496, 'market_cap_rank': 251, 'fully_diluted_valuation': 10263362724, 'total_volume': 286876908, 'high_24h': 91.01, 'low_24h': 90.69, 'price_change_24h': -0.22675979088350573, 'price_change_percentage_24h': -0.24937, 'market_cap_change_24h': 57678327, 'market_cap_change_percentage_24h': 0.5652, 'circulating_supply': 113124007.2800239, 'total_supply': 113132475.412627, 'max_supply': None, 'ath': 92.17, 'ath_change_percentage': -1.59076, 'ath_date': '2026-01-28T15:55:49.024Z', 'atl': 83.77, 'atl_change_percentage': 8.28508, 'atl_date': '2025-05-02T06:32:33.156Z', 'roi': None, 'last_updated': '2026-02-21T06:21:31.012Z'}
{'id': 'apecoin', 'symbol': 'ape', 'name': 'ApeCoin', 'image': 'https://coin-images.coingecko.com/coins/images/24383/large/APECOIN.png?1756551529', 'current_price': 10.33, 'market_cap': 10133027989, 'market_cap_rank': 252, 'fully_diluted_valuation': 10285706444, 'total_volume': 2213269932, 'high_24h': 10.33, 'low_24h': 9.63, 'price_change_24h': 0.390301, 'price_change_percentage_24h': 3.92683, 'market_cap_change_24h': 324617057, 'market_cap_change_percentage_24h': 3.30958, 'circulating_supply': 985156250.0, 'total_supply': 1000000000.0, 'max_supply': 1000000000.0, 'ath': 2044.73, 'ath_change_percentage': -99.49789, 'ath_date': '2022-04-28T21:44:21.164Z', 'atl': 9.63, 'atl_change_percentage': 6.59661, 'atl_date': '2026-02-20T13:40:44.879Z', 'roi': None, 'last_updated': '2026-02-21T06:21:27.652Z'}
{'id': 'melania-meme', 'symbol': 'melania', 'name': 'Melania Meme', 'image': 'https://coin-images.coingecko.com/coins/images/53775/large/melania-meme.png?1737329885', 'current_price': 10.62, 'market_cap': 10110739341, 'market_cap_rank': 253, 'fully_diluted_valuation': 10614950728, 'total_volume': 1276170612, 'high_24h': 11.27, 'low_24h': 10.46, 'price_change_24h': 0.157998, 'price_change_percentage_24h': 1.51066, 'market_cap_change_24h': 90014191, 'market_cap_change_percentage_24h': 0.89828, 'circulating_supply': 952496375.911841, 'total_supply': 999996316.620421, 'max_supply': 1000000000.0, 'ath': 1129.47, 'ath_change_percentage': -99.06009, 'ath_date': '2025-01-20T07:00:55.462Z', 'atl': 7.89, 'atl_change_percentage': 34.53916, 'atl_date': '2025-10-22T22:43:19.403Z', 'roi': None, 'last_updated': '2026-02-21T06:21:33.492Z'}
{'id': 'kamino', 'symbol': 'kmno', 'name': 'Kamino', 'image': 'https://coin-images.coingecko.com/coins/images/35801/large/Kamino_200x200.png?1767944671', 'current_price': 2.52, 'market_cap': 10059142971, 'market_cap_rank': 254, 'fully_diluted_valuation': 25273254572, 'total_volume': 470681065, 'high_24h': 2.56, 'low_24h': 2.46, 'price_change_24h': -0.032636341920804224, 'price_change_percentage_24h': -1.27683, 'market_cap_change_24h': -108543214.48923492, 'market_cap_change_percentage_24h': -1.06753, 'circulating_supply': 3980137186.0, 'total_supply': 9999959303.537935, 'max_supply': 10000000000.0, 'ath': 21.02, 'ath_change_percentage': -87.97564, 'ath_date': '2024-12-15T16:45:25.303Z', 'atl': 1.63, 'atl_change_percentage': 55.09636, 'atl_date': '2024-08-05T13:31:39.944Z', 'roi': None, 'last_updated': '2026-02-21T06:21:32.581Z'}
{'id': 'aztec', 'symbol': 'aztec', 'name': 'Aztec', 'image': 'https://coin-images.coingecko.com/coins/images/70681/large/aztec.png?1763091883', 'current_price': 3.38, 'market_cap': 10056604984, 'market_cap_rank': 255, 'fully_diluted_valuation': 35853941644, 'total_volume': 38205150583, 'high_24h': 3.62, 'low_24h': 2.65, 'price_change_24h': 0.615935, 'price_change_percentage_24h': 22.30949, 'market_cap_change_24h': 2053534290, 'market_cap_change_percentage_24h': 25.65933, 'circulating_supply': 2903052128.0, 'total_supply': 10350000000.0, 'max_supply': 10350000000.0, 'ath': 3.62, 'ath_change_percentage': -4.36924, 'ath_date': '2026-02-21T05:05:24.756Z', 'atl': 1.6, 'atl_change_percentage': 116.48286, 'atl_date': '2026-02-12T07:25:02.723Z', 'roi': None, 'last_updated': '2026-02-21T06:21:28.001Z'}
{'id': 're-protocol-reusd', 'symbol': 'reusd', 'name': 'Re Protocol reUSD', 'image': 'https://coin-images.coingecko.com/coins/images/66291/large/Points_Program_Group_91.png?1749676055', 'current_price': 96.36, 'market_cap': 10026460718, 'market_cap_rank': 256, 'fully_diluted_valuation': 10026460718, 'total_volume': 12823602, 'high_24h': 96.81, 'low_24h': 96.28, 'price_change_24h': -0.21964213292008594, 'price_change_percentage_24h': -0.22743, 'market_cap_change_24h': -12980568.065694809, 'market_cap_change_percentage_24h': -0.1293, 'circulating_supply': 104059738.2226412, 'total_supply': 104059738.2226412, 'max_supply': None, 'ath': 98.49, 'ath_change_percentage': -2.16305, 'ath_date': '2026-01-31T18:55:08.505Z', 'atl': 75.07, 'atl_change_percentage': 28.36569, 'atl_date': '2025-07-17T08:04:08.632Z', 'roi': None, 'last_updated': '2026-02-21T06:21:22.985Z'}
{'id': 'wormhole', 'symbol': 'w', 'name': 'Wormhole', 'image': 'https://coin-images.coingecko.com/coins/images/35087/large/W_Token_%283%29.png?1758122686', 'current_price': 1.83, 'market_cap': 9976824064, 'market_cap_rank': 257, 'fully_diluted_valuation': 18293636585, 'total_volume': 1995810993, 'high_24h': 1.84, 'low_24h': 1.76, 'price_change_24h': 0.04428015, 'price_change_percentage_24h': 2.48075, 'market_cap_change_24h': 227939024, 'market_cap_change_percentage_24h': 2.3381, 'circulating_supply': 5453712835.0, 'total_supply': 10000000000.0, 'max_supply': 10000000000.0, 'ath': 138.37, 'ath_change_percentage': -98.67775, 'ath_date': '2024-04-03T11:46:35.308Z', 'atl': 1.6, 'atl_change_percentage': 14.24744, 'atl_date': '2026-02-06T00:25:56.568Z', 'roi': None, 'last_updated': '2026-02-21T06:21:26.110Z'}
{'id': 'avant-usd', 'symbol': 'avusd', 'name': 'Avant USD', 'image': 'https://coin-images.coingecko.com/coins/images/53527/large/token-avusd.png?1736579003', 'current_price': 90.74, 'market_cap': 9973443902, 'market_cap_rank': 258, 'fully_diluted_valuation': 9973443902, 'total_volume': 5450120, 'high_24h': 91.01, 'low_24h': 90.7, 'price_change_24h': -0.20843271954227305, 'price_change_percentage_24h': -0.22919, 'market_cap_change_24h': 61205916, 'market_cap_change_percentage_24h': 0.61748, 'circulating_supply': 109915587.395903, 'total_supply': 109915587.395903, 'max_supply': None, 'ath': 93.96, 'ath_change_percentage': -3.45078, 'ath_date': '2025-10-10T21:48:29.498Z', 'atl': 83.81, 'atl_change_percentage': 8.24145, 'atl_date': '2025-05-02T06:32:03.463Z', 'roi': None, 'last_updated': '2026-02-21T06:21:30.478Z'}
{'id': 'standx-dusd', 'symbol': 'dusd', 'name': 'StandX DUSD', 'image': 'https://coin-images.coingecko.com/coins/images/55984/large/output-onlinepngtools.png?1747932126', 'current_price': 90.6, 'market_cap': 9787302566, 'market_cap_rank': 259, 'fully_diluted_valuation': 9787302566, 'total_volume': 39731601, 'high_24h': 90.91, 'low_24h': 90.43, 'price_change_24h': -0.22019531155822847, 'price_change_percentage_24h': -0.24245, 'market_cap_change_24h': -24105101.148223877, 'market_cap_change_percentage_24h': -0.24568, 'circulating_supply': 108003381.651646, 'total_supply': 108003381.651646, 'max_supply': None, 'ath': 92.19, 'ath_change_percentage': -1.72074, 'ath_date': '2025-11-21T07:46:31.680Z', 'atl': 84.63, 'atl_change_percentage': 7.0592, 'atl_date': '2025-05-26T04:06:25.299Z', 'roi': None, 'last_updated': '2026-02-21T06:21:24.085Z'}
{'id': 'midas-mf-one', 'symbol': 'mf-one', 'name': 'Midas mF-ONE', 'image': 'https://coin-images.coingecko.com/coins/images/66975/large/mfone-logo.png?1751307469', 'current_price': 96.01, 'market_cap': 9701321418, 'market_cap_rank': 260, 'fully_diluted_valuation': 9701321418, 'total_volume': None, 'high_24h': 96.33, 'low_24h': 95.94, 'price_change_24h': -0.19754310493124194, 'price_change_percentage_24h': -0.20533, 'market_cap_change_24h': -378085659.7481632, 'market_cap_change_percentage_24h': -3.75107, 'circulating_supply': 101028766.2860154, 'total_supply': 101028766.2860154, 'max_supply': None, 'ath': 97.07, 'ath_change_percentage': -1.0848, 'ath_date': '2026-01-28T19:05:05.634Z', 'atl': 86.94, 'atl_change_percentage': 10.43939, 'atl_date': '2025-07-21T08:45:11.072Z', 'roi': None, 'last_updated': '2026-02-21T06:20:01.734Z'}
{'id': 'meteora', 'symbol': 'met', 'name': 'Meteora', 'image': 'https://coin-images.coingecko.com/coins/images/69110/large/meteora.png?1757517561', 'current_price': 19.4, 'market_cap': 9689077051, 'market_cap_rank': 261, 'fully_diluted_valuation': 19357414751, 'total_volume': 961572937, 'high_24h': 19.49, 'low_24h': 18.91, 'price_change_24h': 0.02577989, 'price_change_percentage_24h': 0.13309, 'market_cap_change_24h': 20211470, 'market_cap_change_percentage_24h': 0.20904, 'circulating_supply': 499402297.847091, 'total_supply': 997735631.181012, 'max_supply': 1000000000.0, 'ath': 60.33, 'ath_change_percentage': -67.85743, 'ath_date': '2025-10-23T13:01:20.597Z', 'atl': 16.54, 'atl_change_percentage': 17.25321, 'atl_date': '2026-02-06T00:25:29.859Z', 'roi': None, 'last_updated': '2026-02-21T06:21:33.675Z'}
{'id': 'tokenize-xchange', 'symbol': 'tkx', 'name': 'Tokenize Xchange', 'image': 'https://coin-images.coingecko.com/coins/images/4984/large/TKX_-_Logo_-_RGB-15.png?1696505519', 'current_price': 120.9, 'market_cap': 9662894451, 'market_cap_rank': 262, 'fully_diluted_valuation': 12079222363, 'total_volume': 139242, 'high_24h': 121.71, 'low_24h': 119.25, 'price_change_24h': 0.442456, 'price_change_percentage_24h': 0.3673, 'market_cap_change_24h': 49734464, 'market_cap_change_percentage_24h': 0.51736, 'circulating_supply': 79995997.76037452, 'total_supply': 100000000.0, 'max_supply': 100000000.0, 'ath': 4326.01, 'ath_change_percentage': -97.20518, 'ath_date': '2025-01-03T19:12:43.038Z', 'atl': 7.77, 'atl_change_percentage': 1455.74676, 'atl_date': '2019-04-28T00:00:00.000Z', 'roi': {'times': 3.5871482021192773, 'currency': 'usd', 'percentage': 358.7148202119277}, 'last_updated': '2026-02-21T06:21:24.940Z'}
{'id': 'securitize-tokenized-aaa-clo-fund', 'symbol': 'stac', 'name': 'Securitize Tokenized AAA CLO Fund', 'image': 'https://coin-images.coingecko.com/coins/images/71167/large/stac_logo.png?1766163743', 'current_price': 91418, 'market_cap': 9610192307, 'market_cap_rank': 263, 'fully_diluted_valuation': 9610192307, 'total_volume': None, 'high_24h': 91732, 'low_24h': 91344, 'price_change_24h': -221.181417008469, 'price_change_percentage_24h': -0.24136, 'market_cap_change_24h': -21874653.172029495, 'market_cap_change_percentage_24h': -0.2271, 'circulating_supply': 105099.694673, 'total_supply': 105099.694673, 'max_supply': None, 'ath': 92829, 'ath_change_percentage': -1.50452, 'ath_date': '2026-01-28T19:05:03.513Z', 'atl': 90111, 'atl_change_percentage': 1.46664, 'atl_date': '2026-02-06T00:15:06.823Z', 'roi': None, 'last_updated': '2026-02-21T06:20:03.857Z'}
{'id': 'impossible-cloud-network-token', 'symbol': 'icnt', 'name': 'Impossible Cloud Network Token', 'image': 'https://coin-images.coingecko.com/coins/images/55484/large/ICNT_token_%281%29_%281%29.png?1751614146', 'current_price': 37.77, 'market_cap': 9564464374, 'market_cap_rank': 264, 'fully_diluted_valuation': 26462303774, 'total_volume': 242286297, 'high_24h': 38.24, 'low_24h': 34.37, 'price_change_24h': 2.15, 'price_change_percentage_24h': 6.05018, 'market_cap_change_24h': 577016858, 'market_cap_change_percentage_24h': 6.42025, 'circulating_supply': 253006129.72647312, 'total_supply': 700000000.0, 'max_supply': 700000000.0, 'ath': 52.99, 'ath_change_percentage': -28.44381, 'ath_date': '2025-12-19T14:15:51.293Z', 'atl': 9.76, 'atl_change_percentage': 288.57465, 'atl_date': '2025-10-10T21:43:20.334Z', 'roi': None, 'last_updated': '2026-02-21T06:21:32.093Z'}
{'id': 'oasis-network', 'symbol': 'rose', 'name': 'Oasis', 'image': 'https://coin-images.coingecko.com/coins/images/13162/large/200x200_%28Rounded%29.png?1743579893', 'current_price': 1.26, 'market_cap': 9558553365, 'market_cap_rank': 265, 'fully_diluted_valuation': 12663700259, 'total_volume': 952416956, 'high_24h': 1.27, 'low_24h': 1.13, 'price_change_24h': 0.103529, 'price_change_percentage_24h': 8.97507, 'market_cap_change_24h': 833514987, 'market_cap_change_percentage_24h': 9.55314, 'circulating_supply': 7547994006.0, 'total_supply': 10000000000.0, 'max_supply': 10000000000.0, 'ath': 44.3, 'ath_change_percentage': -97.14725, 'ath_date': '2022-01-15T03:31:11.062Z', 'atl': 0.886267, 'atl_change_percentage': 42.58504, 'atl_date': '2025-12-21T17:40:51.914Z', 'roi': None, 'last_updated': '2026-02-21T06:21:34.382Z'}
{'id': 'gas', 'symbol': 'gas', 'name': 'Gas', 'image': 'https://coin-images.coingecko.com/coins/images/858/large/GAS_512_512.png?1696501992', 'current_price': 146.38, 'market_cap': 9539561526, 'market_cap_rank': 266, 'fully_diluted_valuation': 9539561526, 'total_volume': 167697012, 'high_24h': 147.13, 'low_24h': 141.33, 'price_change_24h': 1.6, 'price_change_percentage_24h': 1.10849, 'market_cap_change_24h': 86826528, 'market_cap_change_percentage_24h': 0.91853, 'circulating_supply': 65093580.54427269, 'total_supply': 65093580.54427269, 'max_supply': None, 'ath': 5841.05, 'ath_change_percentage': -97.49275, 'ath_date': '2018-01-15T00:00:00.000Z', 'atl': 46.91, 'atl_change_percentage': 212.20162, 'atl_date': '2020-03-13T02:24:16.507Z', 'roi': None, 'last_updated': '2026-02-21T06:21:31.976Z'}
{'id': 'zencash', 'symbol': 'zen', 'name': 'Horizen', 'image': 'https://coin-images.coingecko.com/coins/images/691/large/Horizen2.0-logo_icon-on-yellow_%281%29.png?1751696763', 'current_price': 534.69, 'market_cap': 9532411031, 'market_cap_rank': 267, 'fully_diluted_valuation': 11248497936, 'total_volume': 1284331932, 'high_24h': 539.48, 'low_24h': 514.53, 'price_change_24h': 10.86, 'price_change_percentage_24h': 2.07414, 'market_cap_change_24h': 214446345, 'market_cap_change_percentage_24h': 2.30143, 'circulating_supply': 17796210.01729073, 'total_supply': 21000000.0, 'max_supply': 21000000.0, 'ath': 12160.33, 'ath_change_percentage': -95.59903, 'ath_date': '2021-05-08T06:00:30.087Z', 'atl': 216.39, 'atl_change_percentage': 147.32286, 'atl_date': '2017-07-31T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-21T06:21:27.844Z'}
{'id': 'onyc', 'symbol': 'onyc', 'name': 'Onchain Yield Coin', 'image': 'https://coin-images.coingecko.com/coins/images/67072/large/ONyc_Logo_PNG_200px.png?1768587229', 'current_price': 97.8, 'market_cap': 9514022513, 'market_cap_rank': 268, 'fully_diluted_valuation': 9514022513, 'total_volume': 316785393, 'high_24h': 98.14, 'low_24h': 97.71, 'price_change_24h': -0.24856640057963375, 'price_change_percentage_24h': -0.2535, 'market_cap_change_24h': 129749144, 'market_cap_change_percentage_24h': 1.38262, 'circulating_supply': 97274689.45046674, 'total_supply': 97274689.45046674, 'max_supply': None, 'ath': 98.7, 'ath_change_percentage': -0.92093, 'ath_date': '2026-01-28T15:56:54.288Z', 'atl': 86.02, 'atl_change_percentage': 13.69069, 'atl_date': '2025-07-04T14:15:19.160Z', 'roi': None, 'last_updated': '2026-02-21T06:21:34.484Z'}
{'id': 'theta-fuel', 'symbol': 'tfuel', 'name': 'Theta Fuel', 'image': 'https://coin-images.coingecko.com/coins/images/8029/large/1_0YusgngOrriVg4ZYx4wOFQ.png?1696508251', 'current_price': 1.31, 'market_cap': 9513882291, 'market_cap_rank': 269, 'fully_diluted_valuation': 9514232687, 'total_volume': 139007848, 'high_24h': 1.32, 'low_24h': 1.29, 'price_change_24h': 0.01455425, 'price_change_percentage_24h': 1.12147, 'market_cap_change_24h': 110442763, 'market_cap_change_percentage_24h': 1.17449, 'circulating_supply': 7235732536.0, 'total_supply': 7235999028.0, 'max_supply': None, 'ath': 49.72, 'ath_change_percentage': -97.35743, 'ath_date': '2021-06-09T06:50:55.818Z', 'atl': 0.06858, 'atl_change_percentage': 1815.85297, 'atl_date': '2020-03-13T02:30:37.972Z', 'roi': None, 'last_updated': '2026-02-21T06:21:32.201Z'}
{'id': 'sosovalue', 'symbol': 'soso', 'name': 'SoSoValue', 'image': 'https://coin-images.coingecko.com/coins/images/53919/large/soso.jpg?1737717378', 'current_price': 34.5, 'market_cap': 9491716985, 'market_cap_rank': 270, 'fully_diluted_valuation': 34544530776, 'total_volume': 258756658, 'high_24h': 35.49, 'low_24h': 34.13, 'price_change_24h': 0.077449, 'price_change_percentage_24h': 0.22502, 'market_cap_change_24h': 41301456, 'market_cap_change_percentage_24h': 0.43703, 'circulating_supply': 274767576.0, 'total_supply': 1000000000.0, 'max_supply': 1000000000.0, 'ath': 122.43, 'ath_change_percentage': -71.76709, 'ath_date': '2025-01-25T12:11:14.152Z', 'atl': 30.86, 'atl_change_percentage': 11.99004, 'atl_date': '2025-06-08T12:06:07.661Z', 'roi': None, 'last_updated': '2026-02-21T06:21:24.090Z'}
{'id': 'edu-coin', 'symbol': 'edu', 'name': 'Open Campus', 'image': 'https://coin-images.coingecko.com/coins/images/29948/large/EDU_Logo.png?1696528874', 'current_price': 11.29, 'market_cap': 9373740997, 'market_cap_rank': 271, 'fully_diluted_valuation': 11274985426, 'total_volume': 339287268, 'high_24h': 11.54, 'low_24h': 11.13, 'price_change_24h': -0.21070099992945224, 'price_change_percentage_24h': -1.83218, 'market_cap_change_24h': -198132751.98262978, 'market_cap_change_percentage_24h': -2.06995, 'circulating_supply': 831374999.0, 'total_supply': 1000000000.0, 'max_supply': None, 'ath': 136.87, 'ath_change_percentage': -91.75831, 'ath_date': '2023-04-29T08:05:57.583Z', 'atl': 6.35, 'atl_change_percentage': 77.51276, 'atl_date': '2025-10-10T21:33:16.749Z', 'roi': None, 'last_updated': '2026-02-21T06:21:30.408Z'}
{'id': 'cheems-token', 'symbol': 'cheems', 'name': 'Cheems Token', 'image': 'https://coin-images.coingecko.com/coins/images/30376/large/Hg4_Lhbg_400x400.jpg?1696529270', 'current_price': 4.563e-05, 'market_cap': 9287428889, 'market_cap_rank': 272, 'fully_diluted_valuation': 9287428889, 'total_volume': 120603018, 'high_24h': 4.571e-05, 'low_24h': 4.131e-05, 'price_change_24h': 3.2e-06, 'price_change_percentage_24h': 7.53679, 'market_cap_change_24h': 660967813, 'market_cap_change_percentage_24h': 7.6621, 'circulating_supply': 203672952113698.72, 'total_supply': 203672952113698.72, 'max_supply': 219776051832671.0, 'ath': 0.00018517, 'ath_change_percentage': -75.4135, 'ath_date': '2025-03-25T13:56:11.560Z', 'atl': 4.73652e-07, 'atl_change_percentage': 9511.85192, 'atl_date': '2023-09-04T18:45:23.807Z', 'roi': None, 'last_updated': '2026-02-21T06:21:29.174Z'}
{'id': 'verge', 'symbol': 'xvg', 'name': 'Verge', 'image': 'https://coin-images.coingecko.com/coins/images/203/large/Verge_Coin_%28native%29_icon_200x200.jpg?1699220755', 'current_price': 0.559689, 'market_cap': 9240748364, 'market_cap_rank': 273, 'fully_diluted_valuation': 9259232580, 'total_volume': 284859111, 'high_24h': 0.563187, 'low_24h': 0.539673, 'price_change_24h': 0.00475638, 'price_change_percentage_24h': 0.85711, 'market_cap_change_24h': 76023903, 'market_cap_change_percentage_24h': 0.82953, 'circulating_supply': 16521951235.74134, 'total_supply': 16555000000.0, 'max_supply': None, 'ath': 16.76, 'ath_change_percentage': -96.66151, 'ath_date': '2017-12-24T00:00:00.000Z', 'atl': 0.00013839, 'atl_change_percentage': 404339.88005, 'atl_date': '2015-02-06T00:00:00.000Z', 'roi': None, 'last_updated': '2026-02-21T06:21:25.629Z'}

In [ ]:
all_data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 6032988,
  'market_cap': 120700996149603,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 120700996149603,
  'total_volume': 3784806188940,
  'high_24h': 6188629,
  'low_24h': 5848806,
  'price_change_24h': -142748.0134412255,
  'price_change_percentage_24h': -2.31143,
  'market_cap_change_24h': -2798305490953.2812,
  'market_cap_change_percentage_24h': -2.26585,
  'circulating_supply': 19993440.0,
  'total_supply': 19993440.0,
  'max_supply': 21000000.0,
  'ath': 11187013,
  'ath_change_percentage': -46.0715,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 3993.42,
  'atl_change_percentage': 150973.2429,
  'atl_date': '2013-07-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:14.053Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 174620,
  'market_cap': 21095797080775,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 21095797080775,
  'total_volume': 1614586954019,
  'high_24h': 179738,
  'low_24h': 168456,
  'price_change_24h': -4834.605970003991,
  'price_change_percentage_24h': -2.69406,
  'market_cap_change_24h': -560188447741.168,
  'market_cap_change_percentage_24h': -2.58676,
  'circulating_supply': 120692355.0689789,
  'total_supply': 120692355.0689789,
  'max_supply': None,
  'ath': 431946,
  'ath_change_percentage': -59.57369,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 28.13,
  'atl_change_percentage': 620632.26749,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 37.692754146664385,
   'currency': 'btc',
   'percentage': 3769.2754146664383},
  'last_updated': '2026-02-23T10:29:14.538Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 90.88,
  'market_cap': 16688003444148,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 17184845631988,
  'total_volume': 5998348868663,
  'high_24h': 90.88,
  'low_24h': 90.67,
  'price_change_24h': 0.172477,
  'price_change_percentage_24h': 0.19015,
  'market_cap_change_24h': 31502710802,
  'market_cap_change_percentage_24h': 0.18913,
  'circulating_supply': 183624238441.843,
  'total_supply': 189091175734.4462,
  'max_supply': None,
  'ath': 105.52,
  'ath_change_percentage': -13.88094,
  'ath_date': '2025-01-25T16:51:57.989Z',
  'atl': 36.86,
  'atl_change_percentage': 146.53487,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:15.317Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 126.72,
  'market_cap': 7732573358041,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 12670678487670,
  'total_volume': 251678811541,
  'high_24h': 129.19,
  'low_24h': 121.21,
  'price_change_24h': -2.4710630308808703,
  'price_change_percentage_24h': -1.91278,
  'market_cap_change_24h': -148981326288.5254,
  'market_cap_change_percentage_24h': -1.89025,
  'circulating_supply': 61018583977.0,
  'total_supply': 99985712847.0,
  'max_supply': 100000000000.0,
  'ath': 313.99,
  'ath_change_percentage': -59.64288,
  'ath_date': '2025-07-21T15:02:00.541Z',
  'atl': 0.159343,
  'atl_change_percentage': 79424.15798,
  'atl_date': '2013-08-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:15.489Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 55299,
  'market_cap': 7540319722048,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 7540319722048,
  'total_volume': 108322692327,
  'high_24h': 56649,
  'low_24h': 53176,
  'price_change_24h': -1309.2489759605523,
  'price_change_percentage_24h': -2.31281,
  'market_cap_change_24h': -180099576053.4756,
  'market_cap_change_percentage_24h': -2.33277,
  'circulating_supply': 136359026.0799999,
  'total_supply': 136359026.0799999,
  'max_supply': 200000000.0,
  'ath': 121422,
  'ath_change_percentage': -54.45675,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 2.58,
  'atl_change_percentage': 2139363.70254,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:13.999Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 90.88,
  'market_cap': 6764194027684,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 6769787305345,
  'total_volume': 381248875882,
  'high_24h': 90.88,
  'low_24h': 90.68,
  'price_change_24h': 0.154834,
  'price_change_percentage_24h': 0.17066,
  'market_cap_change_24h': 10871839066,
  'market_cap_change_percentage_24h': 0.16099,
  'circulating_supply': 74428856046.35391,
  'total_supply': 74490400889.11264,
  'max_supply': None,
  'ath': 1327.87,
  'ath_change_percentage': -93.15565,
  'ath_date': '2025-01-23T04:45:51.184Z',
  'atl': 65.31,
  'atl_change_percentage': 39.16256,
  'atl_date': '2021-05-19T13:14:05.611Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:16.205Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 7308.23,
  'market_cap': 4153832621400,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 4537119082330,
  'total_volume': 368129246992,
  'high_24h': 7746.6,
  'low_24h': 7013.93,
  'price_change_24h': -423.9367860551538,
  'price_change_percentage_24h': -5.48277,
  'market_cap_change_24h': -241494686020.20117,
  'market_cap_change_percentage_24h': -5.49435,
  'circulating_supply': 568474047.5912273,
  'total_supply': 620928834.6978452,
  'max_supply': None,
  'ath': 25396,
  'ath_change_percentage': -71.22326,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 38.03,
  'atl_change_percentage': 19119.19053,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:13.797Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'current_price': 26.19,
  'market_cap': 2480544657289,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 2480667114002,
  'total_volume': 50101825608,
  'high_24h': 26.4,
  'low_24h': 26.0,
  'price_change_24h': -0.04089139231055938,
  'price_change_percentage_24h': -0.15589,
  'market_cap_change_24h': -4146389038.590332,
  'market_cap_change_percentage_24h': -0.16688,
  'circulating_supply': 94730601626.2116,
  'total_supply': 94735278179.03369,
  'max_supply': None,
  'ath': 36.53,
  'ath_change_percentage': -28.29679,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.117589,
  'atl_change_percentage': 22172.38016,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 150.6570278895448,
   'currency': 'usd',
   'percentage': 15065.702788954479},
  'last_updated': '2026-02-23T10:29:15.630Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 8.78,
  'market_cap': 1482141251600,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 1482344570090,
  'total_volume': 85194391978,
  'high_24h': 8.85,
  'low_24h': 8.34,
  'price_change_24h': -0.047191875114593884,
  'price_change_percentage_24h': -0.53459,
  'market_cap_change_24h': -8454943843.394531,
  'market_cap_change_percentage_24h': -0.56722,
  'circulating_supply': 168830643126.5791,
  'total_supply': 168853803126.5791,
  'max_supply': None,
  'ath': 53.62,
  'ath_change_percentage': -83.6238,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 0.00552883,
  'atl_change_percentage': 158713.72339,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:10.358Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 94.91,
  'market_cap': 1444891708320,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 1444891708320,
  'total_volume': 108352471,
  'high_24h': None,
  'low_24h': None,
  'price_change_24h': None,
  'price_change_percentage_24h': None,
  'market_cap_change_24h': None,
  'market_cap_change_percentage_24h': None,
  'circulating_supply': 15224003657.427,
  'total_supply': 15224003657.427,
  'max_supply': None,
  'ath': 120.96,
  'ath_change_percentage': -21.53923,
  'ath_date': '2025-10-28T06:00:43.161Z',
  'atl': 13.78,
  'atl_change_percentage': 588.50019,
  'atl_date': '2025-10-31T14:57:19.271Z',
  'roi': None,
  'last_updated': '2026-02-22T05:47:52.548Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 49344,
  'market_cap': 987887463030,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 987896261852,
  'total_volume': 32388976444,
  'high_24h': 52259,
  'low_24h': 48879,
  'price_change_24h': -2619.2374677803455,
  'price_change_percentage_24h': -5.0406,
  'market_cap_change_24h': -52285069159.27246,
  'market_cap_change_percentage_24h': -5.02658,
  'circulating_supply': 19998978.02165078,
  'total_supply': 19999265.52165078,
  'max_supply': 21000000.0,
  'ath': 242198,
  'ath_change_percentage': -79.62673,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 5536.54,
  'atl_change_percentage': 791.23648,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:08.254Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 4518.92,
  'market_cap': 965546118195,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 1446948993963,
  'total_volume': 5036651846,
  'high_24h': 4614.6,
  'low_24h': 4388.53,
  'price_change_24h': -88.27115391063126,
  'price_change_percentage_24h': -1.91594,
  'market_cap_change_24h': -18434362430.669434,
  'market_cap_change_percentage_24h': -1.87345,
  'circulating_supply': 213606247.0,
  'total_supply': 320106247.0,
  'max_supply': 400000000.0,
  'ath': 5758.63,
  'ath_change_percentage': -21.6618,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 245.71,
  'atl_change_percentage': 1736.00679,
  'atl_date': '2022-09-21T23:38:03.675Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:16.276Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 24.6,
  'market_cap': 905523460969,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 1106895438521,
  'total_volume': 35961771886,
  'high_24h': 25.11,
  'low_24h': 23.5,
  'price_change_24h': -0.5076701471294598,
  'price_change_percentage_24h': -2.02165,
  'market_cap_change_24h': -19341164197.42639,
  'market_cap_change_percentage_24h': -2.09124,
  'circulating_supply': 36813373987.7429,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 225.26,
  'ath_change_percentage': -89.07756,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 1.38,
  'atl_change_percentage': 1688.84937,
  'atl_date': '2017-11-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:16.024Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 90.86,
  'market_cap': 898432798167,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 898432798167,
  'total_volume': 2220187999,
  'high_24h': 90.88,
  'low_24h': 90.6,
  'price_change_24h': 0.230092,
  'price_change_percentage_24h': 0.25388,
  'market_cap_change_24h': 983098495,
  'market_cap_change_percentage_24h': 0.10954,
  'circulating_supply': 9889121116.640924,
  'total_supply': 9889121116.640924,
  'max_supply': None,
  'ath': 92.23,
  'ath_change_percentage': -1.51475,
  'ath_date': '2026-01-29T16:30:24.390Z',
  'atl': 79.67,
  'atl_change_percentage': 14.0108,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:15.719Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 735.77,
  'market_cap': 677871909183,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 724911699924,
  'total_volume': 301025416,
  'high_24h': 756.74,
  'low_24h': 719.94,
  'price_change_24h': -7.2756733787712164,
  'price_change_percentage_24h': -0.97917,
  'market_cap_change_24h': -6690519109.684204,
  'market_cap_change_percentage_24h': -0.97734,
  'circulating_supply': 921306944.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 888.26,
  'ath_change_percentage': -17.23431,
  'ath_date': '2025-12-01T06:16:28.002Z',
  'atl': 56.97,
  'atl_change_percentage': 1190.37457,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:14.072Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 2552.85,
  'market_cap': 609016866044,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 2458377568450,
  'total_volume': 16502487295,
  'high_24h': 2703.99,
  'low_24h': 2448.78,
  'price_change_24h': -129.31899758262261,
  'price_change_percentage_24h': -4.82143,
  'market_cap_change_24h': -30458300466.908813,
  'market_cap_change_percentage_24h': -4.76302,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'max_supply': 1000000000.0,
  'ath': 5213.52,
  'ath_change_percentage': -51.03398,
  'ath_date': '2025-09-18T03:30:30.650Z',
  'atl': 321.88,
  'atl_change_percentage': 693.10946,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:12.343Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'current_price': 90.76,
  'market_cap': 558073640857,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 558073640857,
  'total_volume': 10747132783,
  'high_24h': 90.87,
  'low_24h': 90.59,
  'price_change_24h': 0.131876,
  'price_change_percentage_24h': 0.14551,
  'market_cap_change_24h': -3397772286.9195557,
  'market_cap_change_percentage_24h': -0.60515,
  'circulating_supply': 6148720059.803138,
  'total_supply': 6148720059.803138,
  'max_supply': None,
  'ath': 92.91,
  'ath_change_percentage': -2.24045,
  'ath_date': '2025-12-09T17:10:12.652Z',
  'atl': 78.05,
  'atl_change_percentage': 16.38333,
  'atl_date': '2024-10-04T07:57:15.809Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:10.888Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 14.67,
  'market_cap': 554559008094,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 554559008094,
  'total_volume': 779625043,
  'high_24h': 14.78,
  'low_24h': 14.25,
  'price_change_24h': 0.190959,
  'price_change_percentage_24h': 1.31879,
  'market_cap_change_24h': 7085727001,
  'market_cap_change_percentage_24h': 1.29426,
  'circulating_supply': 37816248801.26848,
  'total_supply': 37816248801.26848,
  'max_supply': None,
  'ath': 17.72,
  'ath_change_percentage': -17.27912,
  'ath_date': '2026-01-31T16:41:41.560Z',
  'atl': 5.31,
  'atl_change_percentage': 176.15775,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:08.594Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 775.57,
  'market_cap': 549451537323,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 775951928047,
  'total_volume': 31267428898,
  'high_24h': 801.64,
  'low_24h': 743.23,
  'price_change_24h': -25.87281149818034,
  'price_change_percentage_24h': -3.22828,
  'market_cap_change_24h': -17970392583.45941,
  'market_cap_change_percentage_24h': -3.16702,
  'circulating_supply': 708099970.4525867,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 3862.15,
  'ath_change_percentage': -79.91871,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 9.55,
  'atl_change_percentage': 8023.98857,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:08.954Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 29438,
  'market_cap': 543829378458,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 543829378458,
  'total_volume': 7590803852,
  'high_24h': 29780,
  'low_24h': 27947,
  'price_change_24h': 82.4,
  'price_change_percentage_24h': 0.28068,
  'market_cap_change_24h': 2360053750,
  'market_cap_change_percentage_24h': 0.43586,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'max_supply': None,
  'ath': 72026,
  'ath_change_percentage': -59.12832,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 13.57,
  'atl_change_percentage': 216821.77303,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:16.480Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 14.16,
  'market_cap': 464739767041,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 707205272331,
  'total_volume': 8882197197,
  'high_24h': 14.22,
  'low_24h': 13.59,
  'price_change_24h': -0.058545148349345766,
  'price_change_percentage_24h': -0.41182,
  'market_cap_change_24h': -2631954810.803406,
  'market_cap_change_percentage_24h': -0.56314,
  'circulating_supply': 32858661688.61865,
  'total_supply': 50001786883.65895,
  'max_supply': None,
  'ath': 58.01,
  'ath_change_percentage': -75.67997,
  'ath_date': '2021-05-16T09:48:45.220Z',
  'atl': 0.02966141,
  'atl_change_percentage': 47461.3074,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:14.370Z'},
 {'id': 'usd1-wlfi',
  'symbol': 'usd1',
  'name': 'USD1',
  'image': 'https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002',
  'current_price': 90.82,
  'market_cap': 456349718235,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 456349718235,
  'total_volume': 169304835736,
  'high_24h': 90.83,
  'low_24h': 90.59,
  'price_change_24h': 0.169808,
  'price_change_percentage_24h': 0.18732,
  'market_cap_change_24h': -34120930.144470215,
  'market_cap_change_percentage_24h': -0.00748,
  'circulating_supply': 5023324161.228893,
  'total_supply': 5023324161.228893,
  'max_supply': None,
  'ath': 92.17,
  'ath_change_percentage': -1.46597,
  'ath_date': '2026-01-28T15:56:38.616Z',
  'atl': 83.75,
  'atl_change_percentage': 8.43856,
  'atl_date': '2025-05-02T03:46:49.689Z',
  'roi': None,
  'last_updated': '2026-02-23T10:29:15.919Z'},
 {'id': 'rain',
  'symbol': 'rain',
  'name': 'Rain',
  'image': 'https://coin-images.coingecko.com/coins/images/69134/large/Rain_logo_1_.png?1762952191',
  'current_price': 0.879214,
  'market_cap': 420522482908,
  'market_cap_rank': 23,

**data collection:**filter-id, symbol, name, current_price, market_cap, market_cap_rank, total_volume, circulating_supply, total_supply, ath, atl, last_updated(just extract date).

In [ ]:
records =[]
for i in all_data:
  records.append(dict(
      id = i['id'],
      symbol = i['symbol'],
      name=i['name'],
      current_price=i['current_price'],
      market_cap=i['market_cap'],
      market_cap_rank=i['market_cap_rank'],
      total_volume=i['total_volume'],
      circulating_supply=i['circulating_supply'],
      total_supply=i['total_supply'],
      ath=i['ath'],
      atl=i['atl'],
      last_update=i['last_updated']))
records

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'current_price': 6032988,
  'market_cap': 120700996149603,
  'market_cap_rank': 1,
  'total_volume': 3784806188940,
  'circulating_supply': 19993440.0,
  'total_supply': 19993440.0,
  'ath': 11187013,
  'atl': 3993.42,
  'last_update': '2026-02-23T10:29:14.053Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'current_price': 174620,
  'market_cap': 21095797080775,
  'market_cap_rank': 2,
  'total_volume': 1614586954019,
  'circulating_supply': 120692355.0689789,
  'total_supply': 120692355.0689789,
  'ath': 431946,
  'atl': 28.13,
  'last_update': '2026-02-23T10:29:14.538Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'current_price': 90.88,
  'market_cap': 16688003444148,
  'market_cap_rank': 3,
  'total_volume': 5998348868663,
  'circulating_supply': 183624238441.843,
  'total_supply': 189091175734.4462,
  'ath': 105.52,
  'atl': 36.86,
  'last_update': '2026-02-23T10:29:15.317Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'current_price': 126.72,
  'market_cap': 7732573358041,
  'market_cap_rank': 4,
  'total_volume': 251678811541,
  'circulating_supply': 61018583977.0,
  'total_supply': 99985712847.0,
  'ath': 313.99,
  'atl': 0.159343,
  'last_update': '2026-02-23T10:29:15.489Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'current_price': 55299,
  'market_cap': 7540319722048,
  'market_cap_rank': 5,
  'total_volume': 108322692327,
  'circulating_supply': 136359026.0799999,
  'total_supply': 136359026.0799999,
  'ath': 121422,
  'atl': 2.58,
  'last_update': '2026-02-23T10:29:13.999Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'current_price': 90.88,
  'market_cap': 6764194027684,
  'market_cap_rank': 6,
  'total_volume': 381248875882,
  'circulating_supply': 74428856046.35391,
  'total_supply': 74490400889.11264,
  'ath': 1327.87,
  'atl': 65.31,
  'last_update': '2026-02-23T10:29:16.205Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'current_price': 7308.23,
  'market_cap': 4153832621400,
  'market_cap_rank': 7,
  'total_volume': 368129246992,
  'circulating_supply': 568474047.5912273,
  'total_supply': 620928834.6978452,
  'ath': 25396,
  'atl': 38.03,
  'last_update': '2026-02-23T10:29:13.797Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'current_price': 26.19,
  'market_cap': 2480544657289,
  'market_cap_rank': 8,
  'total_volume': 50101825608,
  'circulating_supply': 94730601626.2116,
  'total_supply': 94735278179.03369,
  'ath': 36.53,
  'atl': 0.117589,
  'last_update': '2026-02-23T10:29:15.630Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'current_price': 8.78,
  'market_cap': 1482141251600,
  'market_cap_rank': 9,
  'total_volume': 85194391978,
  'circulating_supply': 168830643126.5791,
  'total_supply': 168853803126.5791,
  'ath': 53.62,
  'atl': 0.00552883,
  'last_update': '2026-02-23T10:29:10.358Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'current_price': 94.91,
  'market_cap': 1444891708320,
  'market_cap_rank': 10,
  'total_volume': 108352471,
  'circulating_supply': 15224003657.427,
  'total_supply': 15224003657.427,
  'ath': 120.96,
  'atl': 13.78,
  'last_update': '2026-02-22T05:47:52.548Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'current_price': 49344,
  'market_cap': 987887463030,
  'market_cap_rank': 11,
  'total_volume': 32388976444,
  'circulating_supply': 19998978.02165078,
  'total_supply': 19999265.52165078,
  'ath': 242198,
  'atl': 5536.54,
  'last_update': '2026-02-23T10:29:08.254Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'current_price': 4518.92,
  'market_cap': 965546118195,
  'market_cap_rank': 12,
  'total_volume': 5036651846,
  'circulating_supply': 213606247.0,
  'total_supply': 320106247.0,
  'ath': 5758.63,
  'atl': 245.71,
  'last_update': '2026-02-23T10:29:16.276Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'current_price': 24.6,
  'market_cap': 905523460969,
  'market_cap_rank': 13,
  'total_volume': 35961771886,
  'circulating_supply': 36813373987.7429,
  'total_supply': 45000000000.0,
  'ath': 225.26,
  'atl': 1.38,
  'last_update': '2026-02-23T10:29:16.024Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'current_price': 90.86,
  'market_cap': 898432798167,
  'market_cap_rank': 14,
  'total_volume': 2220187999,
  'circulating_supply': 9889121116.640924,
  'total_supply': 9889121116.640924,
  'ath': 92.23,
  'atl': 79.67,
  'last_update': '2026-02-23T10:29:15.719Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'current_price': 735.77,
  'market_cap': 677871909183,
  'market_cap_rank': 15,
  'total_volume': 301025416,
  'circulating_supply': 921306944.9,
  'total_supply': 985239504.0,
  'ath': 888.26,
  'atl': 56.97,
  'last_update': '2026-02-23T10:29:14.072Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'current_price': 2552.85,
  'market_cap': 609016866044,
  'market_cap_rank': 16,
  'total_volume': 16502487295,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'ath': 5213.52,
  'atl': 321.88,
  'last_update': '2026-02-23T10:29:12.343Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'current_price': 90.76,
  'market_cap': 558073640857,
  'market_cap_rank': 17,
  'total_volume': 10747132783,
  'circulating_supply': 6148720059.803138,
  'total_supply': 6148720059.803138,
  'ath': 92.91,
  'atl': 78.05,
  'last_update': '2026-02-23T10:29:10.888Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'current_price': 14.67,
  'market_cap': 554559008094,
  'market_cap_rank': 18,
  'total_volume': 779625043,
  'circulating_supply': 37816248801.26848,
  'total_supply': 37816248801.26848,
  'ath': 17.72,
  'atl': 5.31,
  'last_update': '2026-02-23T10:29:08.594Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'current_price': 775.57,
  'market_cap': 549451537323,
  'market_cap_rank': 19,
  'total_volume': 31267428898,
  'circulating_supply': 708099970.4525867,
  'total_supply': 1000000000.0,
  'ath': 3862.15,
  'atl': 9.55,
  'last_update': '2026-02-23T10:29:08.954Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'current_price': 29438,
  'market_cap': 543829378458,
  'market_cap_rank': 20,
  'total_volume': 7590803852,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'ath': 72026,
  'atl': 13.57,
  'last_update': '2026-02-23T10:29:16.480Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'current_price': 14.16,
  'market_cap': 464739767041,
  'market_cap_rank': 21,
  'total_volume': 8882197197,
  'circulating_supply': 32858661688.61865,
  'total_supply': 50001786883.65895,
  'ath': 58.01,
  'atl': 0.02966141,
  'last_update': '2026-02-23T10:29:14.370Z'},
 {'id': 'usd1-wlfi',
  'symbol': 'usd1',
  'name': 'USD1',
  'current_price': 90.82,
  'market_cap': 456349718235,
  'market_cap_rank': 22,
  'total_volume': 169304835736,
  'circulating_supply': 5023324161.228893,
  'total_supply': 5023324161.228893,
  'ath': 92.17,
  'atl': 83.75,
  'last_update': '2026-02-23T10:29:15.919Z'},
 {'id': 'rain',
  'symbol': 'rain',
  'name': 'Rain',
  'current_price': 0.879214,
  'market_cap': 420522482908,
  'market_cap_rank': 23,
  'total_volume': 2549077521,
  'circulating_supply': 477911560666.03564,
  'total_supply': 1149929001319.157,
  'ath': 0.989197,
  'atl': 0.196087,
  'last_update': '2026-02-23T10:29:18.579Z'},
 {'id': 'dai',
  'symbol': 'dai',
  'name': 'Dai',
  'current_price': 90.87,
  'market_cap': 380900604288,
  'market_cap_rank': 24,
  'total_volume': 5840342170,
  'circulating_supply': 4190418004.950516,
  'total_supply': 4190418004.950516,
  'ath': 92.29,
  'atl': 64.85,
  'last_update': '2026-02-23T10:29:09.616Z'},
 {'id': 'hedera-hashgraph',
  'symbol': 'hbar',
  'name': 'Hedera',
  'current_price': 8.76,
  'market_cap': 376891694448,
  'market_cap_rank': 25,
  'total_volume': 7793784128,
  'circulating_supply': 43003421569.20081,
  'total_supply': 50000000000.0,
  'ath': 41.81,
  'atl': 0.703644,
  'last_update': '2026-02-23T10:29:12.115Z'},
 {'id': 'zcash',
  'symbol': 'zec',
  'name': 'Zcash',
  'current_price': 22497,
  'market_cap': 372899537369,
  'market_cap_rank': 26,
  'total_volume': 24059861253,
  'circulating_supply': 16567439.2280448,
  'total_supply': 16567690.7905448,
  'ath': 211171,
  'atl': 1342.38,
  'last_update': '2026-02-23T10:29:17.909Z'},
 {'id': 'paypal-usd',
  'symbol': 'pyusd',
  'name': 'PayPal USD',
  'current_price': 90.88,
  'market_cap': 369650169344,
  'market_cap_rank': 27,
  'total_volume': 6979315804,
  'circulating_supply': 4067584402.503733,
  'total_supply': 4080759746.960552,
  'ath': 92.2,
  'atl': 80.95,
  'last_update': '2026-02-23T10:29:18.068Z'},
 {'id': 'litecoin',
  'symbol': 'ltc',
  'name': 'Litecoin',
  'current_price': 4801.74,
  'market_cap': 369019271662,
  'market_cap_rank': 28,
  'total_volume': 26486949729,
  'circulating_supply': 76879739.48347135,
  'total_supply': 76879739.48347135,
  'ath': 30082,
  'atl': 72.12,
  'last_update': '2026-02-23T10:29:13.786Z'},
 {'id': 'avalanche-2',
  'symbol': 'avax',
  'name': 'Avalanche',
  'current_price': 790.12,
  'market_cap': 341166487749,
  'market_cap_rank': 29,
  'total_volume': 25427500007,
  'circulating_supply': 431771961.1772119,
  'total_supply': 463441061.1772119,
  'ath': 10772.35,
  'atl': 204.63,
  'last_update': '2026-02-23T10:29:08.038Z'},
 {'id': 'shiba-inu',
  'symbol': 'shib',
  'name': 'Shiba Inu',
  'current_price': 0.00055855,
  'market_cap': 329075207884,
  'market_cap_rank': 30,
  'total_volume': 9221301359,
  'circulating_supply': 589243858512311.2,
  'total_supply': 589500400279439.5,
  'ath': 0.00645756,
  'atl': 4.169e-09,
  'last_update': '2026-02-23T10:29:15.927Z'},
 {'id': 'sui',
  'symbol': 'sui',
  'name': 'Sui',
  'current_price': 82.42,
  'market_cap': 317037076437,
  'market_cap_rank': 31,
  'total_volume': 42968486068,
  'circulating_supply': 3846172527.429665,
  'total_supply': 10000000000.0,
  'ath': 458.6,
  'atl': 30.36,
  'last_update': '2026-02-23T10:29:14.555Z'},
 {'id': 'the-open-network',
  'symbol': 'ton',
  'name': 'Toncoin',
  'current_price': 124.18,
  'market_cap': 304424898357,
  'market_cap_rank': 32,
  'total_volume': 8152816845,
  'circulating_supply': 2451016518.171425,
  'total_supply': 5154914722.660754,
  'ath': 689.6,
  'atl': 38.25,
  'last_update': '2026-02-23T10:29:15.198Z'},
 {'id': 'world-liberty-financial',
  'symbol': 'wlfi',
  'name': 'World Liberty Financial',
  'current_price': 10.67,
  'market_cap': 295078868703,
  'market_cap_rank': 33,
  'total_volume': 26008136245,
  'circulating_supply': 27660678305.0,
  'total_supply': 100000000000.0,
  'ath': 29.22,
  'atl': 8.91,
  'last_update': '2026-02-23T10:29:16.526Z'},
 {'id': 'crypto-com-chain',
  'symbol': 'cro',
  'name': 'Cronos',
  'current_price': 6.86,
  'market_cap': 281582394483,
  'market_cap_rank': 34,
  'total_volume': 1094314178,
  'circulating_supply': 41052411580.95372,
  'total_supply': 98418298725.39441,
  'ath': 72.06,
  'atl': 0.864137,
  'last_update': '2026-02-23T10:29:09.418Z'},
 {'id': 'tether-gold',
  'symbol': 'xaut',
  'name': 'Tether Gold',
  'current_price': 466511,
  'market_cap': 242988715134,
  'market_cap_rank': 35,
  'total_volume': 37304124395,
  'circulating_supply': 520825.641697,
  'total_supply': 712747.089,
  'ath': 514631,
  'atl': 108167,
  'last_update': '2026-02-23T10:29:14.846Z'},
 {'id': 'memecore',
  'symbol': 'm',
  'name': 'MemeCore',
  'current_price': 127.02,
  'market_cap': 221107409350,
  'market_cap_rank': 36,
  'total_volume': 1010779825,
  'circulating_supply': 1738882604.031814,
  'total_supply': 5338882603.59109,
  'ath': 260.79,
  'atl': 4.05,
  'last_update': '2026-02-23T10:29:15.480Z'},
 {'id': 'pax-gold',
  'symbol': 'paxg',
  'name': 'PAX Gold',
  'current_price': 469783,
  'market_cap': 215640032892,
  'market_cap_rank': 37,
  'total_volume': 28306213703,
  'circulating_supply': 459009.975,
  'total_supply': 459009.975,
  'ath': 516779,
  'atl': 100361,
  'last_update': '2026-02-23T10:29:18.030Z'},
 {'id': 'uniswap',
  'symbol': 'uni',
  'name': 'Uniswap',
  'current_price': 319.58,
  'market_cap': 202682660639,
  'market_cap_rank': 38,
  'total_volume': 18655546667,
  'circulating_supply': 633696762.0380214,
  'total_supply': 898666420.0366304,
  'ath': 3333.06,
  'atl': 75.81,
  'last_update': '2026-02-23T10:29:16.297Z'},
 {'id': 'polkadot',
  'symbol': 'dot',
  'name': 'Polkadot',
  'current_price': 117.4,
  'market_cap': 195827814357,
  'market_cap_rank': 39,
  'total_volume': 10169767261,
  'circulating_supply': 1668168515.775637,
  'total_supply': 1668168515.775637,
  'ath': 4095.22,
  'atl': 103.91,
  'last_update': '2026-02-23T10:29:18.393Z'},
 {'id': 'blackrock-usd-institutional-digital-liquidity-fund',
  'symbol': 'buidl',
  'name': 'BlackRock USD Institutional Digital Liquidity Fund',
  'current_price': 90.88,
  'market_cap': 176340530888,
  'market_cap_rank': 40,
  'total_volume': None,
  'circulating_supply': 1940292266.820448,
  'total_supply': 1940292266.820448,
  'ath': 92.2,
  'atl': 83.81,
  'last_update': '2026-02-23T10:25:01.862Z'},
 {'id': 'mantle',
  'symbol': 'mnt',
  'name': 'Mantle',
  'current_price': 53.97,
  'market_cap': 175562864968,
  'market_cap_rank': 41,
  'total_volume': 4594276482,
  'circulating_supply': 3252944055.63684,
  'total_supply': 6219316794.889999,
  'ath': 253.43,
  'atl': 25.64,
  'last_update': '2026-02-23T10:29:15.079Z'},
 {'id': 'aave',
  'symbol': 'aave',
  'name': 'Aave',
  'current_price': 10695.32,
  'market_cap': 162483933835,
  'market_cap_rank': 42,
  'total_volume': 24682609939,
  'circulating_supply': 15190669.890452404,
  'total_supply': 16000000.0,
  'ath': 48387,
  'atl': 1933.39,
  'last_update': '2026-02-23T10:29:07.256Z'},
 {'id': 'falcon-finance',
  'symbol': 'usdf',
  'name': 'Falcon USD',
  'current_price': 90.62,
  'market_cap': 159106984044,
  'market_cap_rank': 43,
  'total_volume': 141245392,
  'circulating_supply': 1755667122.206704,
  'total_supply': 1755667122.206704,
  'ath': 92.45,
  'atl': 80.47,
  'last_update': '2026-02-23T10:29:10.958Z'},
 {'id': 'aster-2',
  'symbol': 'aster',
  'name': 'Aster',
  'current_price': 63.91,
  'market_cap': 156800062101,
  'market_cap_rank': 44,
  'total_volume': 12715230188,
  'circulating_supply': 2454947754.91,
  'total_supply': 7822985112.446448,
  'ath': 213.7,
  'atl': 8.76,
  'last_update': '2026-02-23T10:29:15.568Z'},
 {'id': 'pepe',
  'symbol': 'pepe',
  'name': 'Pepe',
  'current_price': 0.00037043,
  'market_cap': 155820129084,
  'market_cap_rank': 45,
  'total_volume': 24384198772,
  'circulating_supply': 420690000000000.0,
  'total_supply': 420690000000000.0,
  'ath': 0.00237833,
  'atl': 4.52e-06,
  'last_update': '2026-02-23T10:29:18.186Z'},
 {'id': 'bittensor',
  'symbol': 'tao',
  'name': 'Bittensor',
  'current_price': 15697.49,
  'market_cap': 150868714477,
  'market_cap_rank': 46,
  'total_volume': 7462894501,
  'circulating_supply': 9597491.0,
  'total_supply': 21000000.0,
  'ath': 62722,
  'atl': 2535.93,
  'last_update': '2026-02-23T10:29:08.209Z'},
 {'id': 'global-dollar',
  'symbol': 'usdg',
  'name': 'Global Dollar',
  'current_price': 90.88,
  'market_cap': 147869378279,
  'market_cap_rank': 47,
  'total_volume': 2948239363,
  'circulating_supply': 1627147250.164927,
  'total_supply': 1627147250.164927,
  'ath': 143.35,
  'atl': 76.61,
  'last_update': '2026-02-23T10:29:11.638Z'},
 {'id': 'okb',
  'symbol': 'okb',
  'name': 'OKB',
  'current_price': 6937.33,
  'market_cap': 145661835759,
  'market_cap_rank': 48,
  'total_volume': 1187380981,
  'circulating_supply': 21000000.0,
  'total_supply': 21000000.0,
  'ath': 22313,
  'atl': 40.86,
  'last_update': '2026-02-23T10:29:17.313Z'},
 {'id': 'hashnote-usyc',
  'symbol': 'usyc',
  'name': 'Circle USYC',
  'current_price': 101.11,
  'market_cap': 144003304098,
  'market_cap_rank': 49,
  'total_volume': 4044.32,
  'circulating_supply': 1553562286.22948,
  'total_supply': 1553562286.22948,
  'ath': 102.4,
  'atl': 86.89,
  'last_update': '2026-02-10T05:42:11.457Z'},
 {'id': 'bitget-token',
  'symbol': 'bgb',
  'name': 'Bitget Token',
  'current_price': 204.83,
  'market_cap': 143438369369,
  'market_cap_rank': 50,
  'total_volume': 1980497951,
  'circulating_supply': 699992035.9787906,
  'total_supply': 916931610.9787906,
  'ath': 722.65,
  'atl': 1.081,
  'last_update': '2026-02-23T10:29:08.344Z'},
 {'id': 'ripple-usd',
  'symbol': 'rlusd',
  'name': 'Ripple USD',
  'current_price': 90.87,
  'market_cap': 141625370518,
  'market_cap_rank': 51,
  'total_volume': 6242625198,
  'circulating_supply': 1558570717.127498,
  'total_supply': 1558570717.127498,
  'ath': 92.15,
  'atl': 81.72,
  'last_update': '2026-02-23T10:29:12.840Z'},
 {'id': 'htx-dao',
  'symbol': 'htx',
  'name': 'HTX DAO',
  'current_price': 0.00015248,
  'market_cap': 139755919607,
  'market_cap_rank': 52,
  'total_volume': 3722492866,
  'circulating_supply': 916533066327098.8,
  'total_supply': 916533066327098.8,
  'ath': 0.00031771,
  'atl': 6.739e-05,
  'last_update': '2026-02-23T10:29:12.204Z'},
 {'id': 'pi-network',
  'symbol': 'pi',
  'name': 'Pi Network',
  'current_price': 14.55,
  'market_cap': 134064438534,
  'market_cap_rank': 53,
  'total_volume': 1402784326,
  'circulating_supply': 9212524148.819681,
  'total_supply': 14173114075.1072,
  'ath': 260.4,
  'atl': 11.91,
  'last_update': '2026-02-23T10:29:18.098Z'},
 {'id': 'sky',
  'symbol': 'sky',
  'name': 'Sky',
  'current_price': 5.73,
  'market_cap': 132099237749,
  'market_cap_rank': 54,
  'total_volume': 881005887,
  'circulating_supply': 23041035146.237114,
  'total_supply': 23462665147.36596,
  'ath': 8.62,
  'atl': 3.12,
  'last_update': '2026-02-23T10:29:13.472Z'},
 {'id': 'bfusd',
  'symbol': 'bfusd',
  'name': 'BFUSD',
  'current_price': 90.81,
  'market_cap': 119858566937,
  'market_cap_rank': 55,
  'total_volume': 500169939,
  'circulating_supply': 1320000000.0,
  'total_supply': 1320000000.0,
  'ath': 92.02,
  'atl': 86.85,
  'last_update': '2026-02-23T10:29:15.068Z'},
 {'id': 'ethereum-classic',
  'symbol': 'etc',
  'name': 'Ethereum Classic',
  'current_price': 767.5,
  'market_cap': 119596106523,
  'market_cap_rank': 56,
  'total_volume': 4942642426,
  'circulating_supply': 155641151.8572869,
  'total_supply': 155644397.8092869,
  'ath': 12296.58,
  'atl': 41.44,
  'last_update': '2026-02-23T10:29:10.918Z'},
 {'id': 'near',
  'symbol': 'near',
  'name': 'NEAR Protocol',
  'current_price': 91.93,
  'market_cap': 118487556134,
  'market_cap_rank': 57,
  'total_volume': 8990812694,
  'circulating_supply': 1288494337.0,
  'total_supply': 1288494755.0,
  'ath': 1518.16,
  'atl': 39.17,
  'last_update': '2026-02-23T10:29:16.971Z'},
 {'id': 'ondo-finance',
  'symbol': 'ondo',
  'name': 'Ondo',
  'current_price': 23.39,
  'market_cap': 113881154321,
  'market_cap_rank': 58,
  'total_volume': 3508633020,
  'circulating_supply': 4869330647.0,
  'total_supply': 10000000000.0,
  'ath': 181.52,
  'atl': 6.83,
  'last_update': '2026-02-23T10:29:17.433Z'},
 {'id': 'superstate-short-duration-us-government-securities-fund-ustb',
  'symbol': 'ustb',
  'name': 'Superstate Short Duration U.S. Government Securities Fund (USTB)',
  'current_price': 999.4,
  'market_cap': 110717810816,
  'market_cap_rank': 59,
  'total_volume': None,
  'circulating_supply': 110784331.405886,
  'total_supply': 110784331.405886,
  'ath': 1011.63,
  'atl': 876.83,
  'last_update': '2026-02-23T10:20:04.719Z'},
 {'id': 'polygon-ecosystem-token',
  'symbol': 'pol',
  'name': 'POL (ex-MATIC)',
  'current_price': 9.92,
  'market_cap': 105253195188,
  'market_cap_rank': 60,
  'total_volume': 5706216731,
  'circulating_supply': 10596603396.79995,
  'total_supply': 10596603396.79995,

In [ ]:
import pandas as pd
df = pd.DataFrame(records)
df.to_csv("records.csv", index=False)

In [ ]:
records[0]

{'id': 'bitcoin',
 'symbol': 'btc',
 'name': 'Bitcoin',
 'current_price': 6032988,
 'market_cap': 120700996149603,
 'market_cap_rank': 1,
 'total_volume': 3784806188940,
 'circulating_supply': 19993440.0,
 'total_supply': 19993440.0,
 'ath': 11187013,
 'atl': 3993.42,
 'last_update': '2026-02-23T10:29:14.053Z'}

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

**Top 3 Coins – Historical Prices **

In [ ]:
import requests
from datetime import datetime
import pandas as pd
hist_prices=[]
coins_id = ["bitcoin","ethereum", "tether"]
for coin_id in coins_id:
 url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"
 print(f"Fetching data for {coin_id} ...")
 response = requests.get(url)

 data=response.json()
 print(data)
 df = pd.DataFrame(data["prices"], columns=[ "date", "price_usd"])

 #df["date"] = pd.to_datetime(df["date"]).dt.date
 #df["date"] = pd.to_datetime(df["date"])
 df["date"] = pd.to_datetime(df["date"], unit="ms").dt.date

 df["coin_id"] = coin_id
 hist_prices.append(df)

hist_df = pd.concat(hist_prices)
print(hist_df)

Fetching data for bitcoin ...

In [ ]:
hist_df.to_csv("hist_prices.csv", index=False)

In [ ]:
hist_df

           date     price_usd  coin_id
0    2025-02-20  96554.871563  bitcoin
1    2025-02-21  98384.317382  bitcoin
2    2025-02-22  96135.155413  bitcoin
3    2025-02-23  96564.154143  bitcoin
4    2025-02-24  96327.463091  bitcoin
..          ...           ...      ...
361  2026-02-16      0.999591   tether
362  2026-02-17      0.999630   tether
363  2026-02-18      0.999656   tether
364  2026-02-19      0.999661   tether
365  2026-02-19      0.999701   tether

[1098 rows x 3 columns]

In [ ]:
hist_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1098 entries, 0 to 365
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       1098 non-null   object
 1   price_usd  1098 non-null   float64
 2   coin_id    1098 non-null   object
dtypes: float64(1), object(2)
memory usage: 34.3+ KB

In [ ]:
len(data)

250

In [ ]:
type(data)

list

**oil prices**

In [ ]:
import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

oil_df

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10095  2026-02-10  64.20
10096  2026-02-11  64.80
10097  2026-02-12  63.08
10098  2026-02-13  63.05
10099  2026-02-17  62.53

[10100 rows x 2 columns]

In [ ]:
import pandas as pd

# Load data
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

# Convert Date column to datetime
oil_df["Date"] = pd.to_datetime(oil_df["Date"])

# Filter Jan 2020 to Jan 2026
filtered_oil_df = oil_df[
    (oil_df["Date"] >= "2020-01-01") &
    (oil_df["Date"] <= "2026-01-31")
]

In [ ]:
filtered_oil_df.to_csv("oil_prices.csv", index=False)

**Stock Prices (Yahoo Finance API)**

In [ ]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-09"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

/tmp/ipython-input-2546641167.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker            ^GSPC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker             ^NSEI
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

In [ ]:
stocks_df['^GSPC'].reset_index()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09
...,...,...,...,...,...,...
1578,2026-02-02,6916.640137,6991.919922,6914.339844,6976.439941,5.772050e+09
1579,2026-02-03,6985.450195,6993.080078,6862.049805,6917.810059,7.017660e+09
1580,2026-02-04,6924.500000,6936.089844,6838.799805,6882.720215,7.475750e+09
1581,2026-02-05,6837.390137,6857.850098,6780.129883,6798.399902,6.989120e+09
1582,2026-02-06,6816.740234,6944.890137,6816.740234,6932.299805,6.283680e+09

In [ ]:
stocks_df1=stocks_df['^GSPC'].reset_index().dropna()
stocks_df1["Ticker"] = "^GSPC"

In [ ]:
stocks_df1

Price,Date,Open,High,Low,Close,Volume,Ticker
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
5,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...
1578,2026-02-02,6916.640137,6991.919922,6914.339844,6976.439941,5.772050e+09,^GSPC
1579,2026-02-03,6985.450195,6993.080078,6862.049805,6917.810059,7.017660e+09,^GSPC
1580,2026-02-04,6924.500000,6936.089844,6838.799805,6882.720215,7.475750e+09,^GSPC
1581,2026-02-05,6837.390137,6857.850098,6780.129883,6798.399902,6.989120e+09,^GSPC
1582,2026-02-06,6816.740234,6944.890137,6816.740234,6932.299805,6.283680e+09,^GSPC

In [ ]:
stocks_df2=stocks_df['^IXIC'].reset_index().dropna()
stocks_df2["Ticker"] = "^IXIC"

In [ ]:
stocks_df3=stocks_df['^NSEI'].reset_index().dropna()
stocks_df3["Ticker"] = "^NSEI"

In [ ]:
final_df = pd.concat([stocks_df1,stocks_df2,stocks_df3], ignore_index=True)
final_df

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...
4572,2026-02-02,24796.500000,25108.099609,24679.400391,25088.400391,4.492000e+05,^NSEI
4573,2026-02-03,26308.050781,26341.199219,25641.300781,25727.550781,6.373000e+05,^NSEI
4574,2026-02-04,25675.050781,25818.550781,25563.949219,25776.000000,4.298000e+05,^NSEI
4575,2026-02-05,25755.900391,25757.650391,25579.500000,25642.800781,3.438000e+05,^NSEI
4576,2026-02-06,25605.800781,25703.949219,25491.900391,25693.699219,3.755000e+05,^NSEI

In [ ]:
final_df.to_csv("stock_prices.csv", index=False)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4577 entries, 0 to 4576
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4577 non-null   datetime64[ns]
 1   Open    4577 non-null   float64
 2   High    4577 non-null   float64
 3   Low     4577 non-null   float64
 4   Close   4577 non-null   float64
 5   Volume  4577 non-null   float64
 6   Ticker  4577 non-null   object
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 250.4+ KB

In [ ]:
final_df.dropna() \
    .reset_index() \
    .to_csv("stock_prices.csv", index=False)

In [ ]:
final_df

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...
4572,2026-02-02,24796.500000,25108.099609,24679.400391,25088.400391,4.492000e+05,^NSEI
4573,2026-02-03,26308.050781,26341.199219,25641.300781,25727.550781,6.373000e+05,^NSEI
4574,2026-02-04,25675.050781,25818.550781,25563.949219,25776.000000,4.298000e+05,^NSEI
4575,2026-02-05,25755.900391,25757.650391,25579.500000,25642.800781,3.438000e+05,^NSEI
4576,2026-02-06,25605.800781,25703.949219,25491.900391,25693.699219,3.755000e+05,^NSEI